# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the fractal dimension of a raster.
#'
#' Calculates the 3D fractal dimension of a raster using the
#' triangular prism surface area method.
#'
#' @param x A raster.
#' @return A numeric value representing the fractal dimension of
#' the image.
#' @examples
#'
#' # import raster image
#' data(normforest)
#'
#' # crop raster to much smaller area
#' x <- crop(normforest, extent(-123, -122.99, 43, 43.01))
#'
#' # calculate the fractal dimension
#' Sfd <- sfd(x)
#' @export
sfd <- function(mat) {
    .Call(`_geodiv_sfd`, mat)
}

